### PR TITLE
Improvements to Notes

### PR DESCRIPTION
**Pull request by k4rtik**
Mostly low-level stuff detected by Grammarly & LTeX (language-tool). I will take a manual pass over the weekend.

### CODE REVIEW

**Comment by ionathanch** [comment]
A few suggestions:
* I don't think there's need to expand all contractions (you'll -> you will, etc.)
* Keep original localization (judgement, analogue)
* Don't change "We will assume that each of the variables in this list *are* distinct from each other"

**Comment by k4rtik** [comment]
Thanks @ionathanch 

> * I don't think there's need to expand all contractions (you'll -> you will, etc.)

I agree and realized it later. Reverting them is too much work, so I am not doing that. Also, after merging changes since my first commit 4 days ago, this PR no longer converts all of them.

> * Keep original localization (judgement, analogue)

It took me quite some time to learn the different spelling of judgement (coming from India/British English). Given this document is mostly written in American English, I made this change. Of course, I am leaving the final decision in Stephanie's hands.

> * Don't change "We will assume that each of the variables in this list _are_ distinct from each other"

Good point. Reverted.

**Comment by k4rtik** [comment]
I am marking this PR ready for review after proofreading until Section 4. I may not have time to look at the rest of the doc until tomorrow.

**Comment by sweirich** [comment]
Thanks for the changes! See you soon.

**Pull request merged**
