### PR TITLE
Allow different branch levels

### PR DESCRIPTION
**Pull request by ionathanch**
In case expressions, the pattern is unified against the scrutinee, so if the constructor's level is different from the inductive's level, the pattern's level will differ from that of the scrutinee, and unification will fail.

### CODE REVIEW

**Comment by sweirich** [comment]
Is this the best way to solve the problem?  Unification of the scrutinee with the pattern should force the scrutinee to a higher level naturally (or require displacing the constructors in the pattern) --- changing the level of the datatype itself shouldn't be necessary, right?

**Comment by ionathanch** [comment]
If you don't make all the levels the same, you're able to do weird things like this:

```ocaml
data Or (A : Type @ 0) (B : Type @ 0) : Type @ 2 where
  Inl of (A) @ 1
  Inr of (B) @ 3
```

But supposing we want to allow this, I think there's two changes that need to be made:

1. Branches where the constructor is at a higher level than the scrutinee should be considered an impossible branch;
2. Relax checking `case` so that patterns in different branches aren't forced to have the same level.

Then the following should type check:

```ocaml
id1 : [A : Type @ 0] -> [B : Type @ 0] -> Or^0 A B -> Or^0 A B @ 2
id1 = \[A] [B] or. case or of
  Inl a -> or
  -- Impossible case: Inr b -> or

id2 : [A : Type @ 0] -> [B : Type @ 0] -> Or^0 A B -> Or^0 A B @ 3
id2 = \[A] [B] or. case or of
  Inl a -> or
  Inr b -> or
```

Does that sound correct? I'll try implementing 2. first, that sounds easier to do.

**Comment by sweirich** [comment]
I was thinking of 2, but 1 is also an intriguing idea.

Right now, level inference doesn't backtrack and occurs after type
checking, so 1 would be difficult to implement.

But if someone wrote an explicit level of 2 for the scrutinee, it would
make sense to rule out Inr as impossible.

--Stephanie

**Comment by ionathanch** [comment]
Here's a slightly different bug with inductives and levels. Suppose we had an inductive whose constructor's level is higher:

```ocaml
data TT : Type @ 0 where
  tt @ 1
```

And then we write a (dependent) function on this inductive:

```ocaml
f : [P : (t : TT^0 @ 0) -> Type @ 1] -> (t : TT^0 @ 0) -> P t @ 2
f = \[P] t. case t of
  tt -> TRUSTME
```

No matter what's in the body of the branch, the branch shouldn't type check at all, because `tt` has level 1, while the scrutinee has level 0, and this results in the branch having type `P tt`, which shouldn't be possible.

However, this currently does type check, since we infer the type of the scrutinee at the ambient level 2, which is valid since it has level 0 in the context, and when then proceed as if the scrutinee has level 2 when it should really be fixed at level 0 because we're destructing it. Should there be a separate mode where we infer both the type and the level? Should case expressions just be specially handled somehow? Some things to consider.

**Review by sweirich — COMMENTED** [review]
I have second thoughts about this. If the expression with the case analysis is displaced to a higher level, then it won't be exhaustive after all.

**Comment by sweirich** [comment]
So, my intuition is that the scrutinee should be forced to have the same level as all of the patterns, and that level should be forced to be less than or equal to the ambient level. The fact that t is still at level 0 (i.e. as a variable it can be used at a higher level) shouldn't be a problem -- if we use f with tt, then we would have had to promote f first, which would also promote P's type.  We do need to think carefully about how definitions with different levels work in the context, though. I.e. when typechecking the body of this case, we get t = tt, which can then be unfolded. Maybe we need to track the current level during whnf?

**Comment by ionathanch** [comment]
> If the expression with the case analysis is displaced to a higher level, then it won't be exhaustive after all.

But displacement will also displace the levels of the patterns too, right? So coming back to `Or`

```ocaml
data Or (A : Type @ 0) (B : Type @ 0) : Type @ 2 where
  Inl of (A) @ 1
  Inr of (B) @ 3
```

If originally we had

```haskell
id2 : [A : Type @ 0] -> [B : Type @ 0] -> Or^0 A B -> Or^0 A B @ 2
id2 = \[A] [B] or. case or of
  Inl a -> Inl a
  -- Impossible case: Inr b -> Inr b
```

Displacing up by 1 would give

```haskell
id2 : [A : Type @ 1] -> [B : Type @ 1] -> Or^1 A B -> Or^1 A B @ 1
id2 = \[A] [B] or. case or of
  Inl^1 a -> Inl^1 a -- inventing some explicit syntax here
  -- Still impossible case: Inr^1 b -> Inr^1 b
```

leaving `Inr^1` still an impossible pattern since it has level 4 while `Or^1` has level 3.

> So, my intuition is that the scrutinee should be forced to have the same level as all of the patterns

If we make the levels of all the patterns the same, maybe we might as well just enforce that the levels of all the constructors be the same then? If you explicitly give constructors different levels, then you can never destruct the inductive properly, and if you leave them implicit, then the moment you write down a case expression, those implicit levels will be constrained to be equal.

You'd then also make the level of the inductive the same as the level of the constructors too, since the level of the scrutinee when not a constructor I think has to come from the level of an inductive written down somewhere.

>  We do need to think carefully about how definitions with different levels work in the context

imo this should be treated the same as types, which is to say that you would never definitionally equate two terms of definitionally inequal types for type soundness (or at least when doing whnf), so you would similarly never definitionally equate two terms at different levels. Maybe with some trickery (keeping track of current level + positivity/negativity to know when we're allowed to use a larger/smaller level??) it would work out, but I have a feeling whoever helps us with the set-theoretic semantics would be upset about that...

Besides, if the scrutinee's level has to be the same as the branch patterns', then the `tt` branch would be ruled out anyway as an ill-typed/impossible branch, and we no longer need to consider equating terms of different levels here.

---

In any case, the scrutinee and pattern levels need to be the same. We can upper-bound the scrutinee's level (currently being done), but it doesn't seem like there would be a way to lower-bound it, so I think the only solution isn't to force the scrutinee's level, but to get the scrutinee's level (concrete or otherwise) and force the patterns' levels (`declarePat` already does this anyway). I'll try to figure out how to get the scrutinee's level from here.

**Comment by ionathanch** [comment]
I found an annotation of [WFU.pi](https://github.com/sweirich/pi-forall/pull/23/files#diff-d81dd617133c68b5f47b56d9014e666a995416544e96b958c25b568c1d633795) that type checks and I'm pretty sure it has to do with some of the level issues we're dealing with right now, but I can't tell what exactly has gone wrong and where the fix is...

**Comment by ionathanch** [comment]
Okay, in the end there are just two major changes:
* Patterns can float up to the ambient level, but the ambient level can't be smaller than the constructor's declared level. This mirrors the constraints added when checking `TCon` and `DCon` (namely `(Le (j0 <> j) mk)`).
   (https://github.com/sweirich/pi-forall/pull/23/files#diff-37bd9d3131beaee8fe816d2c69a76ae33dd11473f9c039d28d9dcc23ab1759bfL452-R445)
* The constructors' levels must be constrained above by the level of the inductive to prevent WFU.pi from type checking. We might revisit this if we ever figure out a reasonable constraint elsewhere to prevent WFU, but for now this seems reasonable. (Maybe open an issue after this PR so we don't forget and it doesn't get lost in the sea of TODOs in the code.)
   (https://github.com/sweirich/pi-forall/pull/23/files#diff-37bd9d3131beaee8fe816d2c69a76ae33dd11473f9c039d28d9dcc23ab1759bfR646)

**Pull request closed without merging**
